#Browser
browser = Chrome
#Base URL
baseURL = https://practice.automationtesting.in
#Username
user_valid=TestGerardo@test.com
user_invalid=WrongUserTestGerardo@test.com
#Psw
psw_valid=HN3b0U68<12
psw_invalid=abc
psw_veryWeak=ab
psw_weak=ab12
psw_medium=2mediumPas
#Error message on invalid password
msg_InvalidPsw=The password you entered for the username
msg_InvalidUser=A user could not be found with this email address.
msg_EmptyPsw=Password is required.
msg_EmptyForm=Username is required.
#Error message on Register form
msg_ExistentUser=An account is already registered with your email address. Please login.
msg_EmptyRegisterForm=Please provide a valid email address.
msg_PasswordVeryWeak=Very weak - Please enter a stronger password.
msg_PasswordWeak=Weak - Please enter a stronger password.
msg_PasswordMedium=Medium
