#Browser
browser = Chrome
#Base URL
baseURL = https://practice.automationtesting.in
#Username
user_valid=TestGerardo@test.com
user_invalid=WrongUserTestGerardo@test.com
#Psw
psw_valid=HN3b0U68<12
psw_invalid=abc
#Error message on invalid password
msg_InvalidPsw=The password you entered for the username
msg_InvalidUser=A user could not be found with this email address.
msg_EmptyPsw=Password is required.
msg_EmptyForm=Username is required.
